import java.util.ArrayList;
import java.util.HashMap;

import org.json.simple.JSONObject;

public class Game {
	
	private static HashMap<String, Game> games = new HashMap<>();
	
	private ArrayList<User> users;
	private User owner;
	private int size;
	private String name;
	private String key;
	
	public Game(User owner, String name, int size) {
		this.owner = owner;
		this.name = name;
		this.size = size;
		this.key = Utils.generateKey();
		
		games.put(this.key, this);
		
		users = new ArrayList<>();
		users.add(owner);
		owner.setGame(this);
		
		System.out.println("Game generated by " + owner.getName() + " of size " + size + " with id " + this.key);
	}
	
	public void start() {
		JSONObject message = new JSONObject();
		message.put("type", "void");
		
		sendToAll(message);
	}
	
	public void sendToAll(JSONObject message) {
		for (User user : users) {
			user.send(message);
		}
	}
	
	public void addUser(User u) {
		users.add(u);
		u.setGame(this);
		
		if (users.size() == size)
			this.start();
	}

	public ArrayList<User> getUsers(){
		return users;
	}
	
	public String getName() {
		return name;
	}
	
	public String getKey() {
		return key;
	}
	
	public static Game getGame(String key) {
		return games.get(key);
	}
}
